# Generated by Django 4.2.1 on 2024-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=89999999999, max_length=15, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
    ]
