# Generated by Django 4.2.1 on 2024-05-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_company_options_alter_user_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("Индивидуальный предприниматель", "ИП"),
                    ("общество с ограниченной ответственностью", "ООО"),
                    ("непубличное акционерное общество", "НАО"),
                    ("публичное акционерное общество", "ПАО"),
                    ("коммерческое товарищество", "КТ"),
                    ("производственный кооператив", "ПК"),
                    ("унитарное предприятие", "УП"),
                    ("хозяйственное товарищество", "ХТ"),
                    ("хозяйственное партнерство", "ХП"),
                    ("некоммерческое юридическое лицо", "НКО"),
                ],
                default="Индивидуальный предприниматель",
                verbose_name="Тип компании",
            ),
        ),
    ]
