# Generated by Django 4.2.1 on 2024-05-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Описание груза"),
                ),
                ("type", models.CharField(max_length=250, verbose_name="Тип груза")),
                ("weight", models.FloatField(default=0, verbose_name="Вес")),
                ("length", models.FloatField(default=0, verbose_name="Длина")),
                ("width", models.FloatField(default=0, verbose_name="Ширина")),
                ("height", models.FloatField(default=0, verbose_name="Высота")),
                ("amount", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "units",
                    models.CharField(
                        choices=[("кг", "килограммы"), ("шт", "штуки"), ("л", "литры")],
                        default="шт",
                        verbose_name="Единицы измерения",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["supply", "-time_create"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Описание"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип доставки",
                "verbose_name_plural": "Типы доставки",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Описание"),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        max_length=20,
                        verbose_name="Цвет для интерфейса",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус доставки",
                "verbose_name_plural": "Статусы доставки",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "start_point_address",
                    models.CharField(max_length=250, verbose_name="Откуда"),
                ),
                (
                    "end_point_address",
                    models.CharField(max_length=250, verbose_name="Куда"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего изменения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(1, "В работе"), (0, "Завершена")],
                        default=1,
                        verbose_name="Статус доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставки",
                "verbose_name_plural": "Доставки",
                "ordering": ["-time_create"],
            },
        ),
        migrations.CreateModel(
            name="SupplyChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "serial_number",
                    models.IntegerField(default=1, verbose_name="Номер по порядку"),
                ),
                (
                    "start_point_address",
                    models.CharField(max_length=250, verbose_name="Откуда"),
                ),
                (
                    "end_point_address",
                    models.CharField(max_length=250, verbose_name="Куда"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего изменения"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Крайний срок")),
                (
                    "delivery_type",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.deliverytype",
                        verbose_name="Тип доставки",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.status",
                        verbose_name="Статус доставки",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supply",
                        verbose_name="Доставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этапы доставки",
                "verbose_name_plural": "Этапы доставки",
                "ordering": ["supply_id", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supply",
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supplychain",
                        verbose_name="Цепь доставки",
                    ),
                ),
            ],
            options={
                "ordering": ["supply", "-time_create"],
            },
        ),
    ]
