# Generated by Django 4.2.1 on 2024-05-12 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="employee",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AddIndex(
            model_name="status",
            index=models.Index(fields=["id"], name="main_status_id_035bcf_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverytype",
            index=models.Index(fields=["id"], name="main_delive_id_55ba5e_idx"),
        ),
        migrations.AddField(
            model_name="cargo",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.supply",
                verbose_name="Доставка",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadfiles",
            index=models.Index(
                fields=["supply", "-time_create"], name="main_upload_supply__5f5885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supply",
            index=models.Index(
                fields=["-time_create"], name="main_supply_time_cr_c2cb15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["supply", "-time_create"], name="main_cargo_supply__23ccee_idx"
            ),
        ),
    ]
