# Generated by Django 4.2.1 on 2024-04-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=500)),
                ("type", models.CharField(max_length=250)),
                ("weight", models.FloatField(default=1)),
                ("length", models.FloatField(default=1)),
                ("width", models.FloatField(default=1)),
                ("height", models.FloatField(default=1)),
                ("amount", models.IntegerField(default=1)),
                ("units", models.CharField(default="шт.", max_length=250)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="supply",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AlterField(
            model_name="supply",
            name="is_active",
            field=models.BooleanField(
                choices=[(1, "Действующая доставка"), (0, "Выполненная доставка")],
                default=1,
            ),
        ),
        migrations.AddIndex(
            model_name="supply",
            index=models.Index(
                fields=["-time_create"], name="main_supply_time_cr_c2cb15_idx"
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="supply_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.supply"
            ),
        ),
    ]
