# Generated by Django 4.2.1 on 2024-05-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0006_alter_company_options_alter_user_company_and_more"),
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="client",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplies_as_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="supplychain",
            name="contractor",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.company",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="employee",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplies_as_employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
    ]
