# Generated by Django 4.2.1 on 2024-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_supply_deadline_alter_cargo_height_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadfiles",
            options={"ordering": ["supply", "supply_chain", "-time_create"]},
        ),
        migrations.RemoveIndex(
            model_name="uploadfiles",
            name="main_upload_supply__5f5885_idx",
        ),
        migrations.AlterField(
            model_name="uploadfiles",
            name="file",
            field=models.FileField(upload_to="", verbose_name="Файл"),
        ),
        migrations.AddIndex(
            model_name="uploadfiles",
            index=models.Index(
                fields=["supply", "supply_chain", "-time_create"],
                name="main_upload_supply__f30b98_idx",
            ),
        ),
    ]
