# Generated by Django 4.2.1 on 2024-05-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_deliverytype_status_supplychain_alter_cargo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplychain",
            name="delivery_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.deliverytype",
                verbose_name="Тип доставки",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="main.status",
                verbose_name="Статус доставки",
            ),
        ),
    ]
