# Generated by Django 4.2.1 on 2024-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_supplychain_delivery_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplychain",
            options={
                "ordering": ["supply_id", "serial_number"],
                "verbose_name": "Этапы доставки",
                "verbose_name_plural": "Этапы доставки",
            },
        ),
        migrations.RemoveIndex(
            model_name="supplychain",
            name="main_supply_time_cr_67e161_idx",
        ),
        migrations.AddField(
            model_name="status",
            name="color",
            field=models.CharField(
                default="gray", max_length=20, verbose_name="Цвет для интерфейса"
            ),
        ),
    ]
