# Generated by Django 4.2.1 on 2024-05-13 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_uploadfiles_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadfiles",
            name="time_update",
        ),
    ]
