# Generated by Django 4.2.1 on 2024-05-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_uploadfiles_time_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_text",
                    models.CharField(max_length=500, verbose_name="Комментарий"),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supply",
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supplychain",
                        verbose_name="Цепь доставки",
                    ),
                ),
            ],
            options={
                "ordering": ["supply", "supply_chain", "-time_create"],
                "indexes": [
                    models.Index(
                        fields=["supply", "supply_chain", "-time_create"],
                        name="main_commen_supply__cd093f_idx",
                    )
                ],
            },
        ),
    ]
