# Generated by Django 4.2.1 on 2024-05-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_supplychain_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supply",
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.supplychain",
                        verbose_name="Цепь доставки",
                    ),
                ),
            ],
            options={
                "ordering": ["supply", "-time_create"],
                "indexes": [
                    models.Index(
                        fields=["supply", "-time_create"],
                        name="main_upload_supply__5f5885_idx",
                    )
                ],
            },
        ),
    ]
