# Generated by Django 4.2.1 on 2024-05-14 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_supply_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplychain",
            name="deadline",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Крайний срок"
            ),
        ),
    ]
