# Generated by Django 4.2.1 on 2024-05-14 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_supplychain_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 16, 26, 56, 926291, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Крайний срок",
            ),
        ),
        migrations.AlterField(
            model_name="supplychain",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 16, 26, 56, 933274, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Крайний срок",
            ),
        ),
    ]
